modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
logoFile="logo.png"
authors="MKUXQQ"
description='''Minecraft 1.21.1 NeoForge 多阶段毒圈 Mod：随机平地缩圈、原版屏障风格边界、安全区探测器与 Xaero 地图兼容。'''
[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="[${neo_version},)"
ordering="NONE"
side="BOTH"
[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"
[[dependencies.${mod_id}]]
modId="xaerominimap"
type="optional"
versionRange="[26.3.0,27.0.0)"
ordering="AFTER"
side="CLIENT"
[[dependencies.${mod_id}]]
modId="xaeroworldmap"
type="optional"
versionRange="[1.43.0,2.0.0)"
ordering="AFTER"
side="CLIENT"
