package com.poisoncircleforge;
import net.minecraft.client.gui.GuiGraphics; import net.minecraft.client.renderer.MultiBufferSource;
import xaero.common.HudMod; import xaero.common.graphics.renderer.multitexture.MultiTextureRenderTypeRendererProvider;
import xaero.hud.minimap.element.render.*; import java.util.*;
final class XaeroMinimapCircleOverlay {
 private XaeroMinimapCircleOverlay(){} static void install(){ HudMod.INSTANCE.getMinimap().getOverMapRendererHandler().add(new Renderer()); }
 private record Pixel(double x,double z,int color){}
 private static final class Provider extends MinimapElementRenderProvider<Pixel,Void>{ List<Pixel> p=List.of();int i; public void begin(MinimapElementRenderLocation l,Void c){i=0;CircleSyncMessage s=PoisonCircleClient.current();if(s==null){p=List.of();return;}List<Pixel> a=new ArrayList<>();add(a,s.x(),s.z(),s.radius(),0xFFFF3030);add(a,s.nextX(),s.nextZ(),s.nextRadius(),0xFFFFFFFF);p=a;} public boolean hasNext(MinimapElementRenderLocation l,Void c){return i<p.size();}public Pixel getNext(MinimapElementRenderLocation l,Void c){return p.get(i++);}public void end(MinimapElementRenderLocation l,Void c){p=List.of();}}
 private static final class Reader extends MinimapElementReader<Pixel,Void>{public boolean isHidden(Pixel p,Void c){return false;}public double getRenderX(Pixel p,Void c,float t){return p.x;}public double getRenderY(Pixel p,Void c,float t){return 0;}public double getRenderZ(Pixel p,Void c,float t){return p.z;}public int getInteractionBoxLeft(Pixel p,Void c,float t){return-1;}public int getInteractionBoxRight(Pixel p,Void c,float t){return 1;}public int getInteractionBoxTop(Pixel p,Void c,float t){return-1;}public int getInteractionBoxBottom(Pixel p,Void c,float t){return 1;}public int getRenderBoxLeft(Pixel p,Void c,float t){return-2;}public int getRenderBoxRight(Pixel p,Void c,float t){return 2;}public int getRenderBoxTop(Pixel p,Void c,float t){return-2;}public int getRenderBoxBottom(Pixel p,Void c,float t){return 2;}public int getLeftSideLength(Pixel p,net.minecraft.client.Minecraft m){return 0;}public String getMenuName(Pixel p){return"";}public String getFilterName(Pixel p){return"";}public int getMenuTextFillLeftPadding(Pixel p){return 0;}public int getRightClickTitleBackgroundColor(Pixel p){return 0;}public boolean shouldScaleBoxWithOptionalScale(){return false;}}
 private static final class Renderer extends MinimapElementRenderer<Pixel,Void>{Renderer(){super(new Reader(),new Provider(),null);}public boolean renderElement(Pixel p,boolean h,boolean o,double d,float s,double x,double z,MinimapElementRenderInfo n,GuiGraphics g,MultiBufferSource.BufferSource b){g.fill(-2,-2,3,3,p.color);return false;}public void preRender(MinimapElementRenderInfo i,MultiBufferSource.BufferSource b,MultiTextureRenderTypeRendererProvider p){}public void postRender(MinimapElementRenderInfo i,MultiBufferSource.BufferSource b,MultiTextureRenderTypeRendererProvider p){}public boolean shouldRender(MinimapElementRenderLocation l){return l==MinimapElementRenderLocation.OVER_MINIMAP;}public int getOrder(){return-100;}}
 private static void add(List<Pixel>a,double x,double z,double r,int c){for(int n=0;n<513;n++){double q=Math.PI*2*n/512;a.add(new Pixel(x+Math.cos(q)*r,z+Math.sin(q)*r,c));}}
}
